In [1]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rc 
rc('text', usetex=False) # switch tex off for using it in the ipython notebook 
import scipy.io
from scipy.interpolate import griddata
from pyDOE import lhs
#from plotting import newfig, savefig
from mpl_toolkits.mplot3d import Axes3D
import time
import matplotlib.gridspec as gridspec
from mpl_toolkits.axes_grid1 import make_axes_locatable

In [2]:
data = scipy.io.loadmat('../Data/NLS.mat')

In [3]:
t = data['tt'].flatten()[:,None]
x = data['x'].flatten()[:,None]
Exact = data['uu']
Exact_u = np.real(Exact)
Exact_v = np.imag(Exact)
Exact_h = np.sqrt(Exact_u**2 + Exact_v**2)

In [10]:
print(t.shape)
print(x.shape)
print(Exact.shape)

(201, 1)
(256, 1)
(256, 201)


In [14]:
X, T = np.meshgrid(x,t)

In [15]:
print(T)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.00785398 0.00785398 0.00785398 ... 0.00785398 0.00785398 0.00785398]
 [0.01570796 0.01570796 0.01570796 ... 0.01570796 0.01570796 0.01570796]
 ...
 [1.55508836 1.55508836 1.55508836 ... 1.55508836 1.55508836 1.55508836]
 [1.56294235 1.56294235 1.56294235 ... 1.56294235 1.56294235 1.56294235]
 [1.57079633 1.57079633 1.57079633 ... 1.57079633 1.57079633 1.57079633]]


In [17]:
# Doman bounds
lb = np.array([-5.0, 0.0])
ub = np.array([5.0, np.pi/2])

N0 = 50
N_b = 50
N_f = 20000

Exact = data['uu']
Exact_u = np.real(Exact)
Exact_v = np.imag(Exact)
Exact_h = np.sqrt(Exact_u**2 + Exact_v**2)

X, T = np.meshgrid(x,t)

#choose training samples randomly 
idx_x = np.random.choice(x.shape[0], N0, replace=False)
x0 = x[idx_x,:]
u0 = Exact_u[idx_x,0:1]
v0 = Exact_v[idx_x,0:1]

idx_t = np.random.choice(t.shape[0], N_b, replace=False)
tb  = t[idx_t,:]

X_f = lb + (ub-lb)*lhs(2, N_f)

In [26]:
Exact_u.shape
X_f.shape
print(X_f)
print(np.max(X_f[:,1]))

[[-3.56470942  0.79416656]
 [ 3.41758839  1.50998765]
 [-2.91500757  0.91047541]
 ...
 [ 1.07550756  0.77849321]
 [-4.2931447   1.28384386]
 [ 3.66770348  1.05565646]]
1.5707337166196667


In [20]:
print(x0.shape)
print(u0.shape,v0.shape)
print(tb.shape)
print(x_F.shape)

(50, 1)
(50, 1) (50, 1)
(50, 1)
